lindcraft/views/model.py
from flask import request, session, g, redirect, url_for, abort, \
     render_template, flash, Blueprint, Response
from users.admin import login_required, table_access_required
from takeabeltof.utils import printException, cleanRecordID
from takeabeltof.date_utils import getDatetimeFromString, local_datetime_now
from lindcraft.models import Product, Category,  Model

mod = Blueprint('model',__name__, template_folder='../templates/lindcraft/admin', url_prefix='/admin/model')


def setExits():
    g.listURL = url_for('.display')
    g.editURL = url_for('.edit')
    g.deleteURL = url_for('.delete')
    g.title = 'Model'


@mod.route('/',methods=["GET",])
@table_access_required(Model)
def display():
    setExits()
    
    recs = Model(g.db).select()
   
    #Get categories to display
    products = Product(g.db)
    product = {}
    #import pdb;pdb.set_trace()
    
    if recs:
        for rec in recs:
            fnd = products.get(rec.prod_id)
            if fnd:
                product[rec.prod_id] = fnd.name

    return render_template('model_list.html',recs=recs,product=product)
    
    
@mod.route('/edit_from_list',methods=["GET", "POST",])
@mod.route('/edit_from_list/',methods=["GET", "POST",])
@mod.route('/edit_from_list/<int:id>/',methods=["GET", "POST",])
@mod.route('/edit_from_list/<int:id>/<int:prod_id>/',methods=["GET", "POST",])
@table_access_required(Model)
def edit_from_list(id=None,prod_id=None):
    """Handle creation of model from the Product record form"""
    setExits()
    #import pdb;pdb.set_trace()
    
    return handle_edit(id,prod_id,from_list=True)
    
@mod.route('/edit',methods=["GET", "POST",])
@mod.route('/edit/',methods=["GET", "POST",])
@mod.route('/edit/<int:id>/',methods=["GET", "POST",])
@table_access_required(Model)
def edit(id=None):
    setExits()
    #import pdb;pdb.set_trace()
    return handle_edit(id,None,from_list=False)

    
def handle_edit(model_id=None,prod_id=None,from_list=False):
    """Handle special parts of model record edit"""

    #import pdb;pdb.set_trace()
    
    products = Product(g.db).select()

    model = Model(g.db)
    model_id = cleanRecordID(model_id)
    rec = model.get(model_id)
    rec_prev = model.get(model_id)
    if rec:
        prod_id = rec.prod_id
        
    current_product = None
    if prod_id == None:
        prod_id = request.form.get('prod_id',0) # attempt to set from form such as in the case of a new model
    prod_id = cleanRecordID(prod_id)
    current_product = Product(g.db).get(prod_id)

    if model_id == 0:
        rec = model.new()
        rec.price_change_date = local_datetime_now()
        rec.prod_id = prod_id
        
        if 'last_model' in session:
            model.update(rec,session['last_model'])
        
    if not rec:
        mes = "not a valid Model ID"
        if from_list:
            return "failure: {}".format(mes)
        else:
            flash(mes)
            return redirect(g.listURL)
             
    # Handle Response?
    if request.form:
        model.update(rec,request.form)
        if validate_form(rec):
    
            if (rec_prev and
                rec.price != rec_prev.price and
                getDatetimeFromString(rec.price_change_date) == getDatetimeFromString(rec_prev.price_change_date)):
                #If the price changed and the date didn't, change the date
                rec.price_change_date = local_datetime_now()
                
            if not rec.prod_id:
                rec.prod_id = prod_id
                
            if save_record(rec):
                if from_list:
                    return "success"
                else:
                    return redirect(g.listURL)
            else:
                if from_list:
                    return "failure: Unable to save changes."
                else:
                    pass #redisplay template below
        else:
            #invalid form
            model.update(rec,request.form)
            
    if from_list:
        return render_template('model_edit_from_list.html',rec=rec,current_product=current_product,products=products)
    else:
        return render_template('model_edit.html',rec=rec,current_product=current_product,products=products)


@mod.route('/get_model_list/',methods=["GET", ])
@mod.route('/get_model_list/<int:prod_id>/',methods=["GET", ])
def get_model_list_for_product(prod_id=None):
    """Render an html snippet of the transaciton list for the product"""
    prod_id = cleanRecordID(prod_id)
    models = None
    if prod_id and prod_id > 0:
        models = Model(g.db).select(where='prod_id = {}'.format(prod_id))
        
    return render_template('model_embed_list.html',models=models,prod_id=prod_id)
    
    
@mod.route('/delete_from_list/',methods=["GET", "POST",])
@mod.route('/delete_from_list/<int:id>/',methods=["GET", "POST",])
@table_access_required(Model)
def delete_from_list(id=None):
    setExits()
    if handle_delete(id):
        return "success"

    return 'failure: Could not delete that {}'.format(g.title)
    
    
@mod.route('/delete',methods=["GET", "POST",])
@mod.route('/delete/',methods=["GET", "POST",])
@mod.route('/delete/<int:id>/',methods=["GET", "POST",])
@table_access_required(Model)
def delete(id=None):
    setExits()
    if handle_delete(id):
        flash("{} Deleted".format(g.title))
        
    return redirect(g.listURL)
    
    
def handle_delete(id=None):
    if id == None:
        id = request.form.get('id',request.args.get('id',-1))
    
    id = cleanRecordID(id)
    if id <=0:
        #flash("That is not a valid record ID")
        return False
        
    rec = Model(g.db).get(id)
    if not rec:
        #flash("Record not found")
        return False
    else:
        Model(g.db).delete(rec.id)
        g.db.commit()
        return True


def save_record(rec):
    """Attempt to save a record"""
    try:
        Model(g.db).save(rec)
        g.db.commit()
        #Save the date and comment to session
        session['last_model'] = {"price_change_date":rec.price_change_date,}
        return True
        
    except Exception as e:
        g.db.rollback()
        flash(printException('Error attempting to save Model record',str(e)))
        return False
    
    
def validate_form(rec):
    valid_form = True
    where = ""
    #import pdb;pdb.set_trace()
    if not rec.model:
        flash("Model Name is required.")
        valid_form = False
    else:
        where = "model = '{}'".format(rec.model.strip())
        if rec.id:
            where += "and id <> {}".format(rec.id)
            
        existing_model_cnt = Model(g.db).select(where=where) #return a row object or None
    
        if existing_model_cnt:
            valid_form = False
            flash('That model name is already taken')
        
    datestring = request.form.get('price_change_date','').strip()
    change_date = getDatetimeFromString(datestring)
    if datestring == '':
        valid_form = False
        flash('Date may not be empty')
        
    elif change_date is None:
        flash('Date is not in a known format ("mm/dd/yy")')
        valid_form = False
    else:
        rec.price_change_date = change_date
        
    # Must be attached to an product
    productID = cleanRecordID(request.form.get('prod_id',0))
    if not productID or productID < 0:
        flash("You must select an product to use with this model")
        valid_form = False
    else:
        # product must exist
        prod = Product(g.db).get(productID)
        if not prod:
            flash("That is not a valid product")
            valid_form = False
            
    # price may not be None
    if rec.price == None:
        flash('The price may not be None')
        valid_form = False
        
    elif type(rec.price) is int or type(rec.price) is float:
        pass #ok
        
    if type(rec.price) is str:
        x = rec.price.partition('.')
        if not x[0].isdigit():
            flash('The price must be a number')
            valid_form = False
        
    return valid_form

lindcraft/templates/lindcraft/admin/category_edit.html
{% extends "layout.html" %}
{% block title %}Edit {{ g.title }}{% endblock %}
{% block body %}
	<h2>Edit {{ g.title }}</h2>	
    <form action="{{ g.editURL }}{{ rec.id|default('0',True)}}/" method=post class="entry">
		{% include "editFormButtons.html" %}
        <fieldset>
    		<input type=hidden name="id" value="{{rec.id|default('0',True )}}">
            <p><span>Name:</span><input type="text" size="20" name="name" required value="{{ rec.name|default('',True )}}" /></p>
            <p><span>Display Order:</span>
                <input type="num" size="10" name="display_order" required value="{{ rec.display_order|default('0',True )}}" />
                &nbsp;<span style="font-size:80%;font-style:italic;font-weight:normal">(Enter a minus number to hide category in main navigation)</span>
            </p>
        </fieldset>
    </form>
{% endblock body %}

lindcraft/templates/lindcraft/admin/category_list.html
{% extends "layout.html" %}
{% block title %}{{ g.title }} List{% endblock %}
{% block body %}
	<h2>{{g.title}} List</h2>
      	<p id="addRecord"><a href="{{ g.editURL }}0/">Add a new {{ g.title }}</a></p>
	{%if recs %}
		<table class="datatable">
		<tr>
			<th>Name</th>
			<th>Order</th>
		</tr>
		{% for rec in recs %}
	    <tr>
			<td style="min-width:100px;"><a href="{{ g.editURL }}{{ rec.id }}/">{{ rec.name }}</a></td>
			<td style="min-width:50px;">{{ rec.display_order }}</td>
		</tr>
		{% endfor %}
	  </table>
  	{% else %}
    	<p><em>No {{ g.title }}s here so far</em></p>
	{% endif %}
{% endblock %}

lindcraft/templates/lindcraft/admin/model_edit.html
{% extends "layout.html" %}
{% block title %}Edit {{ g.title }}{% endblock %}
{% block body %}
	<h2>Edit {{ g.title }}</h2>	
    <form action="{{ g.editURL }}{{ rec.id|default('0',True)}}/" method=post class="entry">
		{% include "editFormButtons.html" %}
        {% include "model_edit_form.html" %}
    </form>
{% endblock body %}

lindcraft/templates/lindcraft/admin/model_edit_form.html
{# Form body for model editing
    
    sql = """
        model TEXT UNIQUE NOT NULL,
        desc TEXT,
        size TEXT,
        bike_cnt INTEGER DEFAULT 1,
        price NUMBER DEFAULT 0,
        active NUMBER DEFAULT 1,
        price_change_date DATETIME,
        prod_id INTEGER,
        
        FOREIGN KEY (prod_id) REFERENCES product(id) ON DELETE CASCADE"""
 #}

<fieldset>
	<input type=hidden name="id" value="{{rec.id|default('0',True )}}">
    {% if products and not current_product %}
    <h3>Select a Product for this Model</h3>
    <select name="prod_id">
        <option value="0"><em>Select one</em></option>
        {% for product in products %}
        <option value="{{product.id}}">{{ product.name}}</option>
        {% endfor %}
    </select>
    {% else %}
		<input type=hidden name="prod_id" value="{{rec.prod_id|default('0',True )}}">
        <h3>Edit Model for {{current_product.name}}</h3>
    {% endif %}
    <p><span>Model Name:</span><input type="num" size="15" name="model" required value="{{ rec.model|default('',True )}}" /></p>
    <p><span>Description:</span><input type="text" size="45" name="desc"  value="{{ rec.desc|default('',True )}}" /></p>
    <p><span>Size:</span><input type="text" size="25" name="size"  value="{{ rec.size|default('',True )}}" /></p>
    <p><span>Bike Count:</span><input type="num" size="5" name="bike_cnt"  value="{{ rec.bike_cnt|default('0', True)}}" /></p>
    <p><span>Price:</span>
        <input type="num" size="10" name="price" value="{{ rec.price|default('0',True )|money}}" />
    </p>
    <p><span>Price Change Date: </span><input type="text" size="20" required name="price_change_date" value="{{ rec.price_change_date|default('',True )|short_date_string}}" /></p>
    <p><span>Active:</span>
        <label><input type="radio" name="active" value="1" {% if rec.active == 1 %} checked="checked" {%endif%} />Active</label>
        &nbsp;&nbsp;
        <label><input type="radio" name="active" value="0" {% if rec.active != 1 %} checked="checked" {%endif%} />Inactive</label>
        
    </p>
</fieldset>

lindcraft/templates/lindcraft/admin/model_edit_from_list.html
{# model form for response to AJAX request #}
{% include "flasher.html"%}
<form id="modelFromListForm"  action="" method="POST">
	<div class="model-buttons data-element">
        {% include "model_edit_form.html"%}
		<p>
		<span class="cancel-link" onclick="cancelModalForm()">Cancel</span>
		<input class="modelSave" type="button" 
            onclick="submitModalForm('modelFromListForm', 
            '{{ url_for('model.edit_from_list')}}{{rec.id | default(0,True)}}/{{ rec.prod_id | default(0,True)}}/', 
            'model_list', 
            '{{ url_for('model.get_model_list_for_product')}}{{ rec.prod_id }}/')" 
            name="Save" value="Save" />
		</p>
	</div>
</form>
</div>

lindcraft/templates/lindcraft/admin/model_embed_list.html
<p><span class="script-link" onclick="editFromList('{{url_for('model.edit_from_list')}}0/{{prod_id}}/')">Add Model...</span></p>
{% if models %}
    <table>
    <tr>
        <th>Model</th>
        <th>Size</th>
        <th>Eff. Date</th>
        <th>Price</th>
        <th>Active</th>
        <th colspan="2">Actions</th>
    </tr>
    {% for model in models %}
        <tr id="model-{{model.id}}">
            <td>{{model.model}}</td>
            <td>{{model.size }}</td>
            <td>{{ model.price_change_date | short_date_string }}</td>
            <td style="text-align:right;">{{ model.price | money }}</td>
            <td style="text-align:center;">{% if model.active == 1 %}
                <img src="{{ url_for('static', filename='images/check_mark.png') }}" />{% else %}
                <img src="{{ url_for('static', filename='images/red_x.png') }}" />
                {%endif%}
            </td>
            <td><span class="script-link" onclick="editFromList('{{ url_for('model.edit_from_list')}}{{ model.id }}/','model_list')">edit</span></td>
            <td><span class="script-link" onclick="$.ajaxSetup({'async' : false});deleteFromList('{{ url_for('model.delete_from_list')}}{{ model.id }}/','model-{{model.id}}');">delete</span></td>
        </tr>
    {% endfor%}
{% else %}
    <p>No Models to list...</p>
    </table>
{% endif %}

lindcraft/templates/lindcraft/admin/model_list.html
{% extends "layout.html" %}
{% block title %}{{ g.title }} List{% endblock %}
{% block body %}
	<h2>{{g.title}} List</h2>
      	<p id="addRecord"><a href="{{ g.editURL }}0/">Add a new {{ g.title }}</a></p>
	{%if recs %}
		<table class="datatable">
		<tr>
            <th>Model</th>
            <th>Desc</th>
            <th>Price</th>
            <th>Active</th>
		</tr>
		{% for rec in recs %}
	    <tr>
			<td style="min-width:80px;"><a href="{{ g.editURL }}{{ rec.id }}/">{{ rec.model }}</a></td>
            <td>{{ rec.desc | default('',True)| truncate(30)}}</td>
            <td style="text-align:right;">{{ rec.price | money }}</td>
            <td style="text-align:center;">{% if rec.active == 1 %}
                <img src="{{ url_for('static', filename='images/check_mark.png') }}" />{% else %}
                <img src="{{ url_for('static', filename='images/red_x.png') }}" />
                {%endif%}
            </td>
		</tr>
		{% endfor %}
	  </table>
  	{% else %}
    	<p><em>No {{ g.title }}s here so far</em></p>
	{% endif %}
{% endblock %}

lindcraft/templates/lindcraft/admin/product_edit.html
{% extends "layout.html" %}
{% block title %}Edit {{ g.title }}{% endblock %}
{% block body %}
	<h2>Edit {{ g.title }}</h2>	
    <div id="product_form">
        <form action="{{ g.editURL }}{{ rec.id|default('0',True)}}/" method=post class="entry">
            {% include "editFormButtons.html" %}
            <fieldset>
                <input type=hidden name="id" value="{{rec.id|default('0',True )}}">
                <p><span>Name:</span><input type="text" size="60" name="name" required value="{{ rec.name|default('',True )}}" /></p>
                <p><span>Description: </span>
                    <textarea name="desc" rows="10" cols="73" style="font-size:.8em;">{{ rec.desc|default('',True ) }}</textarea>
                 </p>
                <p><span>Image: </span><input type="text" size="30" name="image_path" value="{{ rec.image_path|default('',True )}}" /></p>
                <p>Image goes here...</p>
                <p><span>Category: </span>
                    <select  name="cat_id" required >
                        {% if rec.cat_id == None or rec.cat_id == "0" %}
                        <option value="0" ><em>Select One...</em></option>
                        {% endif %}
                        {% for category in categories %}
                        <option value="{{ category.id }}" {% if rec.cat_id == category.id %}selected{% endif %} >{{ category.name}}</option>
                        {% endfor %}
                    </select>
                </p>
            </fieldset>
        </form>
    </div>    
    <div id="model_list">
        <!-- models list will display here -->
        <h3>Models</h3>
        <div id="model_list_body">
        {{ modelList | safe }}
        </div>
    </div>
    
{% endblock body %}

lindcraft/templates/lindcraft/admin/product_list.html
{% extends "layout.html" %}
{% block title %}{{ g.title }} List{% endblock %}
{% block body %}
	<h2>{{g.title}} List</h2>
      	<p id="addRecord"><a href="{{ g.editURL }}0/">Add a new {{ g.title }}</a></p>
	{%if recs %}
		<table class="datatable">
		<tr>
			<th>Name</th>
            <th>Description</th>
		</tr>
		{% for rec in recs %}
	    <tr>
			<td style="min-width:100px;"><a href="{{ g.editURL }}{{ rec.id }}/">{{ rec.name | truncate(20) }}</a></td>
			<td style="min-width:180px;">{{ rec.desc | truncate(80)}}</td>
		</tr>
		{% endfor %}
	  </table>
  	{% else %}
    	<p><em>No {{ g.title }}s here so far</em></p>
	{% endif %}
{% endblock %}