lindcraft/views/catalog.py
from flask import request, session, g, redirect, url_for, abort, \
     render_template, flash, Blueprint, Response
from takeabeltof.utils import printException, cleanRecordID, render_markdown_text
from lindcraft.models import Product, Category,  Model

mod = Blueprint('catalog',__name__, template_folder='../templates/lindcraft/catalog')


def setExits():
    g.title = 'Home'
    g.view_catalog = True
    g.catalog_nav = get_nav_html()


@mod.route('/displayinfo',methods=["GET",])
@mod.route('/displayinfo/',methods=["GET",])
@mod.route('/',methods=["GET",])
def home():
    setExits()
            
    return render_template('home.html',)
    
        
@mod.route('/prices',methods=["GET",])
@mod.route('/prices/',methods=["GET",])
@mod.route('/prices/<prod_id>',methods=["GET",])
@mod.route('/prices/<prod_id>/',methods=["GET",])
@mod.route('/product',methods=["GET",])
@mod.route('/product/',methods=["GET",])
@mod.route('/product/<prod_id>',methods=["GET",])
@mod.route('/product/<prod_id>/',methods=["GET",])
def prices(prod_id=0):
    setExits()
    product_desc_html = ''
    prod_id = cleanRecordID(prod_id)
    price_list = get_price_list(prod_id)
    show_groups = True
    effective_date = get_effective_date()
    if price_list:
        if prod_id <= 0:
            # Price List
            g.title = 'Price List'
            template = 'prices.html'
            
        else:
            # Prices for a single product
            g.title = price_list[0]['product'].name
            show_groups = False
            template = 'product.html'
            product_desc_html = render_markdown_text(price_list[0]['product'].desc)
        return render_template(template,price_list=price_list,show_groups=show_groups,
        effective_date=effective_date,product_desc_html=product_desc_html,)
            
    flash('Could not find that product')
    return redirect(url_for('.home'))
        
    
@mod.route('/display_info/',methods=["GET",])
@mod.route('/display_info/<int:cat_id>',methods=["GET",])
@mod.route('/display_info/<int:cat_id>/',methods=["GET",])
def display_info(cat_id=0):
    setExits()
    cat_id = cleanRecordID(cat_id)
    if cat_id < 1:
        abort(404)
        
    cat = Category(g.db).get(cat_id)
    if not cat:
        abort(404)
        
    recs = Product(g.db).select_active(where="cat_id = {}".format(cat_id))
    if not recs:
        abort(404)
        
    g.title = cat.name
    
    return render_template('display_info.html',recs=recs)
    
    
def get_nav_html():
    """Return fully rendered html for the catalog navigation menu"""
    
    #Create a list to hold a dict of Cat and Product Data for nav display
    cat_list = []
    #Get a selection of categories with active models associated
    cats = Category(g.db).select_active(where="category.display_order >= 0")
    for cat in cats:
        # Get selection of active products for this category
        prods = Product(g.db).select_active(where="cat_id = {}".format(cat.id,))
        if prods:
            cat_list.append({'cat':cat,'prods':prods,})
        
        
    return render_template('nav.html',cat_list=cat_list)
    
    
def get_price_list(prod_id=0):
    """Return a list of dicts with product and model for price list"""
    #import pdb;pdb.set_trace()
    prod_id = cleanRecordID(prod_id)
    prod_list = []
    #Get a selection of products with active models associated
    where = ''
    if prod_id > 0:
        where = "p.id = {}".format(prod_id,)
            
    products = Product(g.db).select_active(where=where)
    if products:
        for product in products:
            # Get selection of active products for this category
            where = 'prod_id = {}'.format(product.id)
            models = Model(g.db).select_active(where=where)
            if models:
                prod_list.append({'product':product,'models':models,})
    
    
    return prod_list
    
    
def get_effective_date():
    """Return the most recent price update date from all models"""
    
    models = Model(g.db).select_one(order_by = 'price_change_date DESC ')
    if models:
        return models.price_change_date
        
    return local_datetime_now() #default to today
    
    
        

www/views/home.py
from flask import request, session, g, redirect, url_for, abort, \
     render_template, flash, Blueprint, Response
from users.admin import login_required, table_access_required
from takeabeltof.date_utils import datetime_as_string
from takeabeltof.utils import render_markdown_for, handle_request_error
from datetime import datetime
from lindcraft.views import catalog

mod = Blueprint('www',__name__, template_folder='../templates', url_prefix='')


def setExits():
    g.homeURL = url_for('.home')
    g.aboutURL = url_for('.about')
    g.contactURL = url_for('.contact')
    g.title = 'Home'
    g.view_catalog = True
    g.catalog_nav = catalog.get_nav_html()
    
@mod.route('/')
def home():
    setExits()

    #rendered_html = render_markdown_for(__file__,mod,'index.md')
    #
    #return render_template('markdown.html',rendered_html=rendered_html,)
    return catalog.home()

@mod.route('/admin', methods=['GET',])
@mod.route('/admin/', methods=['GET',])
def admin_login():
    #Steve is used to entering 'admin' to get to the login page...
    return redirect(url_for('login.login'))
    
    
@mod.route('/about', methods=['GET',])
@mod.route('/about/', methods=['GET',])
def about():
    setExits()
    g.title = "About"
    
    rendered_html = render_markdown_for(__file__,mod,'about.md')
            
    return render_template('about.html',rendered_html=rendered_html)


@mod.route('/contact', methods=['POST', 'GET',])
@mod.route('/contact/', methods=['POST', 'GET',])
def contact():
    setExits()
    g.title = 'Contact Us'
    from app import app
    from takeabeltof.mailer import send_message
    rendered_html = render_markdown_for(__file__,mod,'contact.md')
    show_form = True
    context = {}
    success = True
    passed_quiz = True
    
    mes = "No errors yet..."
    if request.form:
        #import pdb;pdb.set_trace()
        if request.form['email'] and request.form['comment']:
            context.update({'date':datetime_as_string()})
            for key, value in request.form.items():
                context.update({key:value})
                
            # get best contact email
            to = []
            # See if the contact info is in Prefs
            try:
                from users.views.pref import get_contact_email
                contact_to = get_contact_email()
                if contact_to:
                    to.append(contact_to)
            except Exception as e:
                printException("Need to update home.contact to find contacts in prefs.","error",e)
                
            try:
                admin_to = None
                if not to:
                    to = [(app.config['CONTACT_NAME'],app.config['CONTACT_EMAIL_ADDR'],),]
                if app.config['CC_ADMIN_ON_CONTACT']:
                    admin_to = (app.config['MAIL_DEFAULT_SENDER'],app.config['MAIL_DEFAULT_ADDR'],)
                    
                if admin_to:
                    to.append(admin_to,)
                
            except KeyError as e:
                mes = "Could not get email addresses."
                mes = printException(mes,"error",e)
                if to:
                    #we have at least a to address, so continue
                    pass
                else:
                    success = False
                    
            # Grade the quiz
            the_answer = request.form.get('quiz_answer',None)
            if success and (the_answer == None or the_answer !="3"):
                passed_quiz = False
                show_form = False
                return render_template('contact.html',rendered_html=rendered_html, show_form=show_form, context=context,passed_quiz=passed_quiz)
                
            if success:
                # Ok so far... Try to send
                success, mes = send_message(
                                    to,
                                    subject = "Contact from {}".format(app.config['SITE_NAME']),
                                    html_template = "home/email/contact_email.html",
                                    context = context,
                                    reply_to = request.form['email'],
                                )
        
            show_form = False
        else:
            context = request.form
            flash('You left some stuff out.')
            
    if success:
        return render_template('contact.html',rendered_html=rendered_html, show_form=show_form, context=context,passed_quiz=passed_quiz)
            
    handle_request_error(mes,request,500)
    flash(mes)
    return render_template('500.html'), 500
    
    
@mod.route('/robots.txt', methods=['GET',])
def robots():
    resp = Response("""User-agent: *
Disallow: /""" )
    resp.headers['content-type'] = 'text/plain'
    return resp

templates/editFormButtons.html
<p class="form_button_row" >
	<input type=submit value=Save />&nbsp;&nbsp;
	{% if rec.id and rec.id > 0 and (not no_delete or is_admin) and not g.cancelURL %}
	<a id="form_delete_link" href = "{{g.deleteURL}}{{rec.id}}/" onclick="return confirmRecordDelete();">Delete...</a>&nbsp;&nbsp;
	{% endif %}
    <a href="{% if g.cancelURL %}{{g.cancelURL}}{% else %}{{ g.listURL }}{% endif %}" >Cancel</a>
</p> 

templates/flasher.html
{% with messages = get_flashed_messages() %} {% if messages %} 
<div class="clear" id="flasher_contain">
	{% for message in messages %} 
	<p class="flash">
		{{ message }}
	</p>
	{% endfor %} 
</div>
{% endif %} {% endwith %}

templates/footer.html
<div id="foot">
    <p class="noprint">
    	<strong>LINDCRAFT</strong>&nbsp;&nbsp;-&nbsp;&nbsp;1-800-326-0965&nbsp;&nbsp;-&nbsp;&nbsp;
    	Fax:&nbsp;1-916-985-7731&nbsp;&nbsp;-&nbsp;
    	<span class="contactLink"><a href="{{ url_for( 'www.contact') }}">Contact Us</a></span>
    	<span class="contactPrint">www.LindcraftRacks.biz</span>
    </p>
</div>

templates/header.html
<div id="head">
    <div id="logoblock">
        <p id="bikelogo">
    	<a href="{{ url_for( 'www.home') }}" ><img  src="{{ url_for('static', filename= 'images/BikesLogo.gif') }}" /></a>
        </p>
        <p id="lcrlogo" >
    	<a href="{{ url_for( 'www.home') }}" ><img src="{{ url_for('static', filename='images/Lindcraft_Logo.gif') }}" /></a>
        </p>
    	<h2>BICYCLE DISPLAY FIXTURES</h2>
    </div>
</div>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title%}{{g.title}}{% endblock %} - {{ config.SITE_NAME | default("",True) }}</title> 
	<link rel="icon" type="image/png" href="{{ url_for('static', filename='bikes.png') }}" >
    <link rel="SHORTCUT ICON" type="image/vnd.microsoft.icon" href="{{ url_for('static', filename='bikes.ico') }}" >
    <link rel="apple-touch-icon" type="image/png" href="{{ url_for('static', filename='apple-touch-icon-57.png') }}"><!-- iPhone -->
    <link rel="apple-touch-icon" type="image/png" sizes="72x72" href="{{ url_for('static', filename='apple-touch-icon-72.png') }}"><!-- iPad -->
    <link rel="apple-touch-icon" type="image/png" sizes="114x114" href="{{ url_for('static', filename='apple-touch-icon-114.png') }}"><!-- iPhone4 -->
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='apple-touch-icon-114.png') }}"><!-- Opera Speed Dial, at least 144×114 px -->
    
	<link rel=stylesheet type=textcss href="{{ url_for('static', filename='css/style.css') }}">
    {% if g.view_catalog %}
	<link rel="stylesheet" href="{{ url_for('static',filename='css/lindcraft.css') }}" type="textcss" media="all" >
	<link rel="stylesheet" href="{{ url_for('static',filename='css/lindcraft.print.css') }}" type="textcss" media="print" >
	{% endif %}
    
    {% if not g.view_catalog or g.user %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
	<script src="{{ url_for('static', filename='common.js') }}"></script>
    {% endif %}

    {% block head%}{% endblock %}
</head>
<body>
<div id="contain">
    <div id="dialog"></div><div id="modal-form-contain"><div id="modal-form"></div></div>
    <div class="no-print">
    {% include "header.html"%}
    {% include "top-nav.html"%}
    </div>
	{% include "flasher.html" %}
	{% block body %}{% endblock %} 
    {% if g.view_catalog %}
        {% block nav %}{% if g.catalog_nav %}{{g.catalog_nav | safe }}{%endif%}{% endblock %}
        <div class="content">
            <div id="stage">
                {% block content %}{% endblock %}
            </div>
        </div>
        {% include "footer.html"%}
    {% endif %}
</div>
</body>
</html>

templates/nav.html
<div class="catalog-nav noprint" >
    <p id="catalog-menu-header" onclick="" >Catalog Menu</p>
    <div id="catalog-menu-contain">
        {% for cat in cat_list %}
    	<div  class="catalog-nav_background">
    		<p><a href="{{ url_for( 'catalog.display_info' ) }}{{ cat['cat'].id }}/" >{{cat['cat'].name}}</a></p>
    	</div>
    	<div class="catalog-nav_image_group" >
    		<p>
    			{% for product in cat['prods'] %}
    			<a href="{{ url_for( 'catalog.prices') }}{{ product.id }}/"  title="{{ product.name }}">
                    <img class="catalog-nav_image" src="/static/{{ product.image_path | small_product_image }}" 
                    alt="{{ product.name }}">
                </a>
    			{% endfor %}
    		</p>
    	</div>
        {% endfor %}

    	<div class="catalog-nav_background">
    			<p><a href="{{ url_for( 'catalog.prices') }}" >Price List</a></p>
    	</div>


    	<div class="catalog-nav_background">
    			<p><a href="{{ url_for( 'www.contact') }}" >Special Quotes</a></p>
    	</div>


    	<div class="catalog-nav_background">
    			<p><a href="{{ url_for( 'www.about') }}" >About Lindcraft</a></p>
    	</div>
    </div>
    <p class="clear"></p>
    
</div>

templates/top-nav.html
{% if g.user %}
    <div id="nav">
        <p id="mobile-menu-header" class="menu-item dropdown" onclick="" >Menu</p>
        <div id="mobile-menu-contain">
            <div>
                <p class="menu-item" ><a href="/">Home</a></p>
            </div>
            <div onclick="" id="profile-menu" class="dropdown">
                <p class="dd-menu-header">
                    {% if g.user %}My Profile{% else %}<a href="{{ url_for('login.login')}}" >Login</a>{% endif %}
                </p>
                <div class="dropdown-content">
                    <ul>
                        {% if g.user %}
                        <li><a href="{{ url_for('user.edit')}}" >Manage Profile</a></li>
                        <li><a href="{{ url_for('login.logout')}}">Logout</a></li>
                            {% if g.admin and g.admin.has_access(g.user)%}
                                {% for item in g.admin.permissions %}
                                    {% if g.admin.has_access(g.user,item['table'])%}
                                        {% if item['header_row'] == True %}
                                        <p class="dd-menu-divider">{{item['display_name']}}</p>
                                        {% else %}
                                        <li><a href="{{item['url']}}">{{item['display_name']}}</a></li>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <p class="clear"></p>
    </div>
{% else %}
    <p class="clear"></p>
{% endif %}